export const PENDIK_NEIGHBORHOODS = [
  "Bahçelievler",
  "Batı",
  "Çamçeşme",
  "Çamlık",
  "Çınardere",
  "Doğu",
  "Dumlupınar",
  "Ertuğrul Gazi",
  "Esenler",
  "Esenyalı",
  "Fatih",
  "Fevzi Çakmak",
  "Güllübağlar",
  "Güzelyalı",
  "Harmandere",
  "Kavakpınar",
  "Kaynarca",
  "Kurtköy",
  "Orhangazi",
  "Orta",
  "Ramazanoğlu",
  "Sapanbağları",
  "Sülüntepe",
  "Şeyhli",
  "Velibaba",
  "Yayalar",
  "Yeni Mahalle",
  "Yenişehir",
] as const;

export type PendikNeighborhood = (typeof PENDIK_NEIGHBORHOODS)[number];
